config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "homes#index"
  resources :posts
  resources :tags
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :tags
  validates :title, :description, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @posts = Post.all
    @tags = Tag.all
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new

    respond_to do |format|
      format.html { redirect_to homes_path }
      format.js
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:notice] = "write something, friend."
      redirect_to root_path
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html { redirect_to root_path }
      format.js
    end
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:notice] = "write something, friend."
      redirect_to root_path
    end
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homes/index.html.erb
<h4>Say Something.</h4>


<ul id="each_post">
  <% @posts.each do |post| %>
    <li><%= post.title %> | <%= post.description %></li>
  <% end %>
</ul>

<ul id="each_tag">
  <% @tags.each do |tag| %>
    <li><%= tag.name %> </li>
  <% end %>
</ul>

<div id="link_container">
  <%= link_to "say something", new_post_path, :id => "new_post_link", :remote => true %> |

  <%= link_to "tag something", new_tag_path, :id => "new_tag_link", :remote => true %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Something</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>


    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class"navbar-header">
          <a class="navbar-brand" href="/">Okay Go</a>
        </div>
        <div>
          <ul class="nav navbar-nav">
            <li><a href="/">Home</a></li>
          </ul>
        </div>
      </div>
    </nav>



    <div class="user_nav">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> |
        <%= link_to "Login", new_user_session_path %>
      <% end %>
    </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}" %>
    <% end %>
    <%= yield %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 4, class: "form-control" %>
  </div>
  <%= f.submit "Submit", class: "btn btn-default center-block" %>
<% end %>

app/views/posts/create.js.erb
$('form').remove();
$('#each_post').append("<li><%= @post.title %> | <%= post.description %></li>");
$('#new_post_link').show();

app/views/posts/new.js.erb
$('#new_post_link').hide();
$('#each_post').append("<%= j render 'form' %>");

app/views/tags/_form.html.erb
<%= form_for @tag do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.submit "Submit", class: "btn btn-default center-block" %>
<% end %>

app/views/tags/new.js.erb
$('#new_tag_link').hide();
$('#link_container').append("<%= j render 'form' %>");

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>